name: Pull Request Check

on:
  workflow_dispatch:  # allows manual triggering
  pull_request:

jobs:
  run-changed-r:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Download source data from Azure Blob
      run: |
        az storage blob download-batch \
          --account-name <your_storage_account_name> \
          --destination ./data \
          --source <your_container_name> \
          --auth-mode login

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install remotes package
      run: Rscript -e 'install.packages("remotes")'

    - name: Install carobiner package from GitHub
      run: Rscript -e 'remotes::install_github("reagro/carobiner", dependencies = TRUE, force = TRUE, upgrade = "never")'

    # - name: Get changed R files
    #   id: changed
    #   run: |
    #     CHANGED_FILES=$(git diff --name-only origin/main...HEAD | grep '\.R$' || true)
    #     echo "changed_files=$CHANGED_FILES" >> $GITHUB_OUTPUT

    - name: Run review of R scripts
      if: steps.changed.outputs.changed_files != ''
      run: |
        Rscript -e "source('scripts/eia/NT7VLWDrOQEkarWkfn2bDSuf.R'); carob_script()"
        # for file in ${{ steps.changed.outputs.changed_files }}; do
        #   echo "Running $file"
        #   Rscript -e "source('$file'); carob_script()"
        # done
